//! LOG.md generation from LogRecords.
//!
//! This module generates LOG.md content from a list of LogRecords.
//! The generation is deterministic: the same records always produce the same output.

use crate::state::{LogAction, LogData, LogRecord};

/// Maximum length for content previews before truncation.
const MAX_PREVIEW_LENGTH: usize = 500;

/// Generate LOG.md content from a list of log records.
///
/// The generated markdown follows the format defined in the existing LOG.md template,
/// with entries sorted chronologically by timestamp.
///
/// # Arguments
///
/// * `records` - The log records to generate markdown from
///
/// # Returns
///
/// A string containing the complete LOG.md content.
pub fn generate_log_md(records: &[LogRecord]) -> String {
    let mut output = String::new();

    // Header
    output.push_str("# Claude Code Manager - Execution Log\n\n");
    output.push_str("This file is automatically generated from tasks.json log records.\n\n");
    output.push_str("---\n\n");

    if records.is_empty() {
        output.push_str("No log entries yet.\n");
        return output;
    }

    // Group records by phase
    let mut current_phase: Option<String> = None;

    for record in records {
        // Check if we need a new phase header
        if let Some(ref phase_id) = record.phase_id {
            if current_phase.as_ref() != Some(phase_id) {
                if current_phase.is_some() {
                    output.push_str("\n---\n\n");
                }
                current_phase = Some(phase_id.clone());
            }
        }

        // Format the record
        output.push_str(&format_record(record));
        output.push('\n');
    }

    output
}

/// Format a single log record as markdown.
fn format_record(record: &LogRecord) -> String {
    let timestamp = record.timestamp.format("%Y-%m-%d %H:%M:%S UTC");
    let action_name = format_action(&record.action);

    let mut parts = vec![format!("[{}] **{}**", timestamp, action_name)];

    if let Some(ref phase_id) = record.phase_id {
        parts.push(format!("Phase: {}", phase_id));
    }

    if let Some(ref task_id) = record.task_id {
        parts.push(format!("Task: {}", task_id));
    }

    if let Some(ref agent_id) = record.agent_id {
        parts.push(format!("Agent: {}", agent_id));
    }

    let header = parts.join(" | ");
    let details = format_data(&record.data);

    format!("{}\n\n{}\n", header, details)
}

/// Format the action type as a display string.
fn format_action(action: &LogAction) -> &'static str {
    match action {
        LogAction::PhaseStart => "PHASE_START",
        LogAction::TaskStart => "TASK_START",
        LogAction::AgentSpawn => "AGENT_SPAWN",
        LogAction::AgentComplete => "AGENT_COMPLETE",
        LogAction::BuildResult => "BUILD_RESULT",
        LogAction::ReviewResult => "REVIEW_RESULT",
        LogAction::TaskComplete => "TASK_COMPLETE",
        LogAction::TaskDeferred => "TASK_DEFERRED",
        LogAction::Error => "ERROR",
        LogAction::Shutdown => "SHUTDOWN",
    }
}

/// Format the log data payload as markdown.
fn format_data(data: &LogData) -> String {
    match data {
        LogData::PhaseStart { name } => {
            format!("## Phase: {}\n", name)
        }

        LogData::TaskStart { name } => {
            format!("### Task: {}\n", name)
        }

        LogData::AgentSpawn {
            agent_type,
            prompt_preview,
        } => {
            let truncated = truncate_content(prompt_preview, MAX_PREVIEW_LENGTH);
            format!(
                "### Agent Spawn\n\n**Type:** {}\n\n<details>\n<summary>Prompt Preview</summary>\n\n```\n{}\n```\n\n</details>",
                agent_type, truncated
            )
        }

        LogData::AgentComplete {
            exit_code,
            duration_secs,
        } => {
            format!(
                "### Agent Complete\n\n**Exit Code:** {}\n**Duration:** {}s\n",
                exit_code, duration_secs
            )
        }

        LogData::BuildResult {
            success,
            errors,
            warnings,
        } => {
            let status = if *success { "PASS" } else { "FAIL" };
            let mut result = format!("### Build Result: {}\n\n", status);

            if !errors.is_empty() {
                result.push_str("**Errors:**\n");
                for error in errors {
                    result.push_str(&format!("- {}\n", error));
                }
                result.push('\n');
            }

            if !warnings.is_empty() {
                result.push_str("**Warnings:**\n");
                for warning in warnings {
                    result.push_str(&format!("- {}\n", warning));
                }
                result.push('\n');
            }

            result
        }

        LogData::ReviewResult {
            verdict,
            issues_count,
        } => {
            format!(
                "### Review Result: {}\n\n**Issues Found:** {}\n",
                verdict.to_uppercase(),
                issues_count
            )
        }

        LogData::TaskComplete { status } => {
            format!("Task completed with status: **{}**\n", status)
        }

        LogData::TaskDeferred { reason } => {
            format!("Task deferred.\n\n**Reason:** {}\n", reason)
        }

        LogData::Error { message } => {
            format!("**Error:** {}\n", message)
        }

        LogData::Shutdown { reason } => {
            format!(
                "### Graceful Shutdown\n\n**Reason:** {}\n\nExecution can be resumed by running the manager again.\n",
                reason
            )
        }
    }
}

/// Truncate content to a maximum length, adding an indicator if truncated.
fn truncate_content(content: &str, max_len: usize) -> String {
    if content.len() <= max_len {
        content.to_string()
    } else {
        let truncated = &content[..max_len];
        format!(
            "{}\n\n... [truncated, {} more bytes]",
            truncated,
            content.len() - max_len
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use chrono::Utc;

    fn make_record(action: LogAction, data: LogData) -> LogRecord {
        LogRecord {
            id: "test-id".to_string(),
            timestamp: Utc::now(),
            action,
            phase_id: None,
            task_id: None,
            agent_id: None,
            data,
        }
    }

    #[test]
    fn test_generate_log_md_empty() {
        let output = generate_log_md(&[]);
        assert!(output.contains("# Claude Code Manager - Execution Log"));
        assert!(output.contains("No log entries yet."));
    }

    #[test]
    fn test_generate_log_md_with_records() {
        let records = vec![
            make_record(
                LogAction::PhaseStart,
                LogData::PhaseStart {
                    name: "Setup".to_string(),
                },
            ),
            make_record(
                LogAction::TaskStart,
                LogData::TaskStart {
                    name: "Initialize project".to_string(),
                },
            ),
        ];

        let output = generate_log_md(&records);
        assert!(output.contains("PHASE_START"));
        assert!(output.contains("TASK_START"));
        assert!(output.contains("## Phase: Setup"));
        assert!(output.contains("### Task: Initialize project"));
    }

    #[test]
    fn test_format_build_result_success() {
        let data = LogData::BuildResult {
            success: true,
            errors: vec![],
            warnings: vec![],
        };

        let output = format_data(&data);
        assert!(output.contains("### Build Result: PASS"));
    }

    #[test]
    fn test_format_build_result_failure() {
        let data = LogData::BuildResult {
            success: false,
            errors: vec!["unresolved import".to_string()],
            warnings: vec!["unused variable".to_string()],
        };

        let output = format_data(&data);
        assert!(output.contains("### Build Result: FAIL"));
        assert!(output.contains("**Errors:**"));
        assert!(output.contains("unresolved import"));
        assert!(output.contains("**Warnings:**"));
        assert!(output.contains("unused variable"));
    }

    #[test]
    fn test_format_agent_spawn() {
        let data = LogData::AgentSpawn {
            agent_type: "implem".to_string(),
            prompt_preview: "Implement feature X".to_string(),
        };

        let output = format_data(&data);
        assert!(output.contains("### Agent Spawn"));
        assert!(output.contains("**Type:** implem"));
        assert!(output.contains("Implement feature X"));
    }

    #[test]
    fn test_format_review_result() {
        let data = LogData::ReviewResult {
            verdict: "approved".to_string(),
            issues_count: 0,
        };

        let output = format_data(&data);
        assert!(output.contains("### Review Result: APPROVED"));
        assert!(output.contains("**Issues Found:** 0"));
    }

    #[test]
    fn test_format_shutdown() {
        let data = LogData::Shutdown {
            reason: "Received SIGINT".to_string(),
        };

        let output = format_data(&data);
        assert!(output.contains("### Graceful Shutdown"));
        assert!(output.contains("Received SIGINT"));
        assert!(output.contains("resumed"));
    }

    #[test]
    fn test_truncate_content() {
        let short = "short text";
        assert_eq!(truncate_content(short, 100), short);

        let long = "x".repeat(200);
        let truncated = truncate_content(&long, 100);
        assert!(truncated.contains("[truncated"));
        assert!(truncated.contains("100 more bytes"));
    }

    #[test]
    fn test_record_with_context() {
        let mut record = make_record(
            LogAction::AgentSpawn,
            LogData::AgentSpawn {
                agent_type: "implem".to_string(),
                prompt_preview: "Test".to_string(),
            },
        );
        record.phase_id = Some("phase-1".to_string());
        record.task_id = Some("task-1".to_string());
        record.agent_id = Some("agent-123".to_string());

        let output = format_record(&record);
        assert!(output.contains("Phase: phase-1"));
        assert!(output.contains("Task: task-1"));
        assert!(output.contains("Agent: agent-123"));
    }
}
